// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnXUeu8IHU8IRpgMujmMVYe32sRdy-63c',
    appId: '1:961740823486:web:0506d6ab13915c7fb5f7ef',
    messagingSenderId: '961740823486',
    projectId: 'soulsync-dairyapp',
    authDomain: 'soulsync-dairyapp.firebaseapp.com',
    storageBucket: 'soulsync-dairyapp.firebasestorage.app',
    measurementId: 'G-ZKJ3NY7MHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnNbKhE5gPWZp5rLhvk9tkurxQ9FOJJA',
    appId: '1:961740823486:android:c88fe552647ff978b5f7ef',
    messagingSenderId: '961740823486',
    projectId: 'soulsync-dairyapp',
    storageBucket: 'soulsync-dairyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5v6CVY4YxfLZA4UAK_XA0IWnTVlECbw',
    appId: '1:961740823486:ios:7b8cc348f8fb7ffbb5f7ef',
    messagingSenderId: '961740823486',
    projectId: 'soulsync-dairyapp',
    storageBucket: 'soulsync-dairyapp.firebasestorage.app',
    iosBundleId: 'com.example.soulsyncDairyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc5v6CVY4YxfLZA4UAK_XA0IWnTVlECbw',
    appId: '1:961740823486:ios:7b8cc348f8fb7ffbb5f7ef',
    messagingSenderId: '961740823486',
    projectId: 'soulsync-dairyapp',
    storageBucket: 'soulsync-dairyapp.firebasestorage.app',
    iosBundleId: 'com.example.soulsyncDairyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnXUeu8IHU8IRpgMujmMVYe32sRdy-63c',
    appId: '1:961740823486:web:ae1a749bb46f3918b5f7ef',
    messagingSenderId: '961740823486',
    projectId: 'soulsync-dairyapp',
    authDomain: 'soulsync-dairyapp.firebaseapp.com',
    storageBucket: 'soulsync-dairyapp.firebasestorage.app',
    measurementId: 'G-8YRM7R0VD2',
  );
}
